/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appTienda.c1_presentacion.form;

import appTienda.c1_presentacion.util.Mensaje;
import appTienda.c2_aplicacion.servicio.GestionarCargoServicio;
import appTienda.c2_aplicacion.servicio.GestionarUsuarioServicio;
import appTienda.c3_dominio.entidad.Cargo;
import appTienda.c3_dominio.entidad.Usuario;
import com.sun.glass.events.KeyEvent;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.util.ArrayList;

/**
 *
 * @author Osorio Perez Carlos - hacybeyker@gmail.com
 */
public class FormLogin extends javax.swing.JFrame {

    int contador = 0;
    ArrayList<Cargo> listaCargo;
    Usuario usuario;
    /**
     * Creates new form FormLogin
     */
    public FormLogin() {
        mostrarLookAndFeel();
        initComponents();
        iniciar();
        this.usuario = new Usuario();
        mostrarIcono();
        LlenarComboCargo();
        this.contador=0;
    }

    private void LlenarComboCargo(){
        try{            
            GestionarCargoServicio gestionarCargoServicio = new GestionarCargoServicio();
            listaCargo = gestionarCargoServicio.buscarPorNombre(null);
            comboCargo.removeAllItems();
            for (Cargo cargo : listaCargo) {
                comboCargo.addItem(cargo.getNombre());
            }
            comboCargo.setSelectedIndex(-1);
        }catch(Exception ex){
            
        }
    }
    
    private void mostrarLookAndFeel() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }
    
    private void iniciar(){
        textoUser.setText("");
        textoPassword.setText("");
        comboCargo.setSelectedIndex(-1);
        textoUser.requestFocus();
    }
    
    private void mostrarIcono() {        
        URL recurso = getClass().getResource("/appTienda/c5_recursos/iconos/logox32.png");
        Image icono = Toolkit.getDefaultToolkit().createImage(recurso);
        setIconImage(icono);
    }
    
    private boolean verificarCampos(){
        boolean estado;
        if(!textoUser.getText().trim().isEmpty()){
            if(comboCargo.getSelectedIndex()!=-1){
                if(!textoPassword.getText().trim().isEmpty()){
                   estado = true;
                }else{
                    textoPassword.requestFocus();
                    estado = false;
                }
            }else{
                comboCargo.requestFocus(); 
                comboCargo.setPopupVisible(true);
                estado = false;
            }
        }else{
            textoUser.requestFocus();
            estado = false;
        }
        return estado;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textoUser = new javax.swing.JTextField();
        comboCargo = new javax.swing.JComboBox();
        textoPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appTienda/c5_recursos/iconos/cargox20.png"))); // NOI18N
        jLabel3.setText("Cargo:");
        jLabel3.setOpaque(true);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appTienda/c5_recursos/iconos/passx20.png"))); // NOI18N
        jLabel4.setText("Password:");
        jLabel4.setOpaque(true);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appTienda/c5_recursos/iconos/empleadox20.png"))); // NOI18N
        jLabel2.setText("Usuario:");
        jLabel2.setOpaque(true);

        textoUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textoUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textoUserKeyPressed(evt);
            }
        });

        comboCargo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboCargo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                comboCargoKeyPressed(evt);
            }
        });

        textoPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textoPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textoPasswordKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textoUser)
                    .addComponent(comboCargo, 0, 175, Short.MAX_VALUE)
                    .addComponent(textoPassword))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel2))
                            .addComponent(textoUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(comboCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void textoUserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoUserKeyPressed
        ingresarEnter(evt);
    }//GEN-LAST:event_textoUserKeyPressed

    private void textoPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoPasswordKeyPressed
        // TODO add your handling code here:
        ingresarEnter(evt);
    }//GEN-LAST:event_textoPasswordKeyPressed

    private void comboCargoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comboCargoKeyPressed
        // TODO add your handling code here:
        ingresarEnter(evt);
    }//GEN-LAST:event_comboCargoKeyPressed

    private void ingresarEnter(java.awt.event.KeyEvent evt) throws HeadlessException {
        // TODO add your handling code here:   
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(verificarCampos()){
                if(verificarUsuario()){
                    FormMenu formMenu = new FormMenu(usuario);
                    formMenu.setVisible(true);
                    this.dispose();
                }else{
                    contador++;
                    Mensaje.Mostrar_MENSAJE_AVISOINTENTOS(this, contador);
                    if(contador>=3)
                        System.exit(0);
                }                
            }
        }
        
    }
    
    public boolean verificarUsuario(){
        boolean usuarioCorrecto;
        GestionarUsuarioServicio gestionarUsuarioServicio = new GestionarUsuarioServicio();
        String user,tipo,password;
        user = textoUser.getText().trim().toUpperCase();
        tipo = comboCargo.getSelectedItem().toString();
        password = textoPassword.getText().trim();
        try {
            usuario = gestionarUsuarioServicio.IngresoUsuario(user, tipo, password);
            if(usuario!=null){
                usuarioCorrecto = true;
            }else{
                usuarioCorrecto = false;
            }
        } catch (Exception ex) {
            usuarioCorrecto = false;
        }
        return usuarioCorrecto;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboCargo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField textoPassword;
    private javax.swing.JTextField textoUser;
    // End of variables declaration//GEN-END:variables
}
