/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appTienda.c1_presentacion.form;

import appTienda.c1_presentacion.util.Mensaje;
import appTienda.c2_aplicacion.servicio.GestionarProductoServicio;
import appTienda.c3_dominio.entidad.Producto;
import java.awt.Dialog;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;
import mastersoft.modelo.ModeloTabla;
import mastersoft.tabladatos.Columna;
import mastersoft.tabladatos.Fila;
import mastersoft.tabladatos.Tabla;

/**
 *
 * @author Osorio Perez Carlos - hacybeyker@gmail.com
 */
public class FormGestionarProducto extends javax.swing.JDialog {

    ArrayList<Producto> listaProducto;
    
    /**
     * Creates new form FormGestionarProducto
     * @param parent
     * @param modal
     */
    public FormGestionarProducto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();  
        setResizable(false);
        crearTabla();
    }

    //Para abrir desde Registrar Venta
    
    public FormGestionarProducto(Dialog owner) {
        super(owner, true);
        initComponents();  
        setResizable(false);
        crearTabla();
        botonSeleccionar.setEnabled(true);
    }

    private void crearTabla() {
        Tabla tabla_Producto = new Tabla();
        tabla_Producto.agregarColumna(new Columna("Codigo", "java.lang.Integer"));
        tabla_Producto.agregarColumna(new Columna("Nombre", "java.lang.String"));
        tabla_Producto.agregarColumna(new Columna("Tipo Producto", "java.lang.String"));
        tabla_Producto.agregarColumna(new Columna("U. Medida", "java.lang.String"));
        tabla_Producto.agregarColumna(new Columna("Marca", "java.lang.String"));
        tabla_Producto.agregarColumna(new Columna("Descripcion", "java.lang.String"));
        tabla_Producto.agregarColumna(new Columna("Stock", "java.lang.Integer"));
        tabla_Producto.agregarColumna(new Columna("Precio", "java.lang.Double"));
        
        ModeloTabla modeloTablaProducto = new ModeloTabla(tabla_Producto);
        tablaProducto.setModel(modeloTablaProducto );
        
        TableColumn columna0,columna1,columna2,columna3,columna4,columna5,columna6,columna7;
        //Codigo
        columna0 = tablaProducto.getColumnModel().getColumn(0);
        columna0.setPreferredWidth(150);
        columna0.setMaxWidth(200);
        columna0.setMinWidth(150);
        //Nombre
        columna1 = tablaProducto.getColumnModel().getColumn(1);
        columna1.setPreferredWidth(140);
        columna1.setMaxWidth(250);
        columna1.setMinWidth(140);
        //Tipo Producto
        columna2 = tablaProducto.getColumnModel().getColumn(2);
        columna2.setPreferredWidth(120);
        columna2.setMaxWidth(160);
        columna2.setMinWidth(120);
        //Unidad de Medida
        columna3 = tablaProducto.getColumnModel().getColumn(3);
        columna3.setPreferredWidth(65);
        columna3.setMaxWidth(75);
        columna3.setMinWidth(65);
        //Marca
        columna4 = tablaProducto.getColumnModel().getColumn(4);
        columna4.setPreferredWidth(100);
        columna4.setMaxWidth(120);
        columna4.setMinWidth(100);
        //Descripcion
        columna5 = tablaProducto.getColumnModel().getColumn(5);
        columna5.setPreferredWidth(250);
        columna5.setMaxWidth(300);
        columna5.setMinWidth(250);
        //Stock
        columna6 = tablaProducto.getColumnModel().getColumn(6);
        columna6.setPreferredWidth(60);
        columna6.setMaxWidth(70);
        columna6.setMinWidth(60);
        //Precio
        columna7 = tablaProducto.getColumnModel().getColumn(7);
        columna7.setPreferredWidth(55);
        columna7.setMaxWidth(60);
        columna7.setMinWidth(55);
        tablaProducto.removeColumn(columna0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        botonCrear = new javax.swing.JButton();
        botonModificar = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textobuscar = new javax.swing.JTextField();
        botonBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProducto = new javax.swing.JTable();
        botonSeleccionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestionar Producto");

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        botonCrear.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botonCrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appTienda/c5_recursos/iconos/crearx32.png"))); // NOI18N
        botonCrear.setText("Crear");
        botonCrear.setFocusable(false);
        botonCrear.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonCrear.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearActionPerformed(evt);
            }
        });
        jToolBar1.add(botonCrear);

        botonModificar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botonModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appTienda/c5_recursos/iconos/modificarx32.png"))); // NOI18N
        botonModificar.setText("Modificar");
        botonModificar.setFocusable(false);
        botonModificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonModificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarActionPerformed(evt);
            }
        });
        jToolBar1.add(botonModificar);

        botonEliminar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appTienda/c5_recursos/iconos/eliminarx32.png"))); // NOI18N
        botonEliminar.setText("Eliminar");
        botonEliminar.setFocusable(false);
        botonEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });
        jToolBar1.add(botonEliminar);

        botonSalir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appTienda/c5_recursos/iconos/salirx32.png"))); // NOI18N
        botonSalir.setText("Salir");
        botonSalir.setFocusable(false);
        botonSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        jToolBar1.add(botonSalir);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Nombre:");

        textobuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        botonBuscar.setBackground(new java.awt.Color(255, 255, 255));
        botonBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appTienda/c5_recursos/iconos/buscarx20.png"))); // NOI18N
        botonBuscar.setText("Buscar");
        botonBuscar.setOpaque(false);
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        tablaProducto.setAutoCreateRowSorter(true);
        tablaProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaProducto);

        botonSeleccionar.setBackground(new java.awt.Color(255, 255, 255));
        botonSeleccionar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonSeleccionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appTienda/c5_recursos/iconos/Seleccionarx20.png"))); // NOI18N
        botonSeleccionar.setText("Seleccionar");
        botonSeleccionar.setEnabled(false);
        botonSeleccionar.setMaximumSize(new java.awt.Dimension(97, 29));
        botonSeleccionar.setMinimumSize(new java.awt.Dimension(97, 29));
        botonSeleccionar.setOpaque(false);
        botonSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSeleccionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 823, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textobuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textobuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBuscar)
                    .addComponent(botonSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearActionPerformed
        // TODO add your handling code here:
        FormRegistrarProducto formRegistrarProducto = new FormRegistrarProducto(this);
        formRegistrarProducto.setVisible(true);
    }//GEN-LAST:event_botonCrearActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        // TODO add your handling code here:
        if(!textobuscar.getText().trim().isEmpty()){
            consultarProducto();
            ponerFocoConSeleccionEnBuscar();            
        }else{            
            Mensaje.Mostrar_MENSAJE_LLENARCAMPOBUSCAR(this);            
            ponerFocoConSeleccionEnBuscar();
        }
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void botonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarActionPerformed
        // TODO add your handling code here:
        int tipoProductoid = obtenerCodigoDeLaTabla();
        if(tipoProductoid == 0)
            return;
        GestionarProductoServicio gestionarProductoServicio = new GestionarProductoServicio();    
        try {
            Producto producto = gestionarProductoServicio.buscar(tipoProductoid);
            if(producto != null){
                FormRegistrarProducto formRegistrarProducto = new FormRegistrarProducto(this, producto);
                formRegistrarProducto.setVisible(true);
            }
            else{
                Mensaje.Mostrar_MENSAJE_FILANOEXISTE(this);
            }
            crearTabla();
            ponerFocoConSeleccionEnBuscar();
        } catch(Exception e){
            //Mensaje.mostrarErrorDeConsulta(this);
        }  
    }//GEN-LAST:event_botonModificarActionPerformed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        // TODO add your handling code here:
        int productoid = obtenerCodigoDeLaTabla();
        if(productoid == 0)
            return;
        if(!Mensaje.Mostrar_MENSAJE_PREGUNTADEELIMINACION(this))
            return;
        GestionarProductoServicio gestionarProductoServicio = new GestionarProductoServicio();                    
        try {
            int registros_afectados = gestionarProductoServicio.eliminar(obtenerCodigoDeLaTabla());
            if(registros_afectados == 1){
                Mensaje.Mostrar_MENSAJE_ELIMINACIONEXITOSA(this);                
            }else{
                Mensaje.Mostrar_MENSAJE_ELIMINACIONERRONEA(this);
            }
            crearTabla();
            ponerFocoConSeleccionEnBuscar();
        } catch(Exception e){
            //JOptionPane.showMessageDialog(panelContenedor, e.getMessage());
        }  
    }//GEN-LAST:event_botonEliminarActionPerformed

    private void botonSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSeleccionarActionPerformed
        // TODO add your handling code here:
        int tipoProductoid = obtenerCodigoDeLaTabla();
        //int cantidad = Mensaje.Mostrar_MENSAJE_INGRESARCANTIDAD(this);
        if(tipoProductoid == 0)
            return;
        GestionarProductoServicio gestionarProductoServicio = new GestionarProductoServicio();    
        try {
            Producto producto = gestionarProductoServicio.buscar(tipoProductoid);
            if(producto != null){
                FormRegistrarPedido formRegistrarPedido = new FormRegistrarPedido(this, producto);
                this.dispose();
            }
            else{
                Mensaje.Mostrar_MENSAJE_FILANOEXISTE(this);
            }
            crearTabla();
            ponerFocoConSeleccionEnBuscar();
        } catch(Exception e){
            //Mensaje.mostrarErrorDeConsulta(this);
        }  
        
    }//GEN-LAST:event_botonSeleccionarActionPerformed

    private int obtenerCodigoDeLaTabla() {
        int numFila = tablaProducto.getSelectedRow();
        if(numFila == -1){
            Mensaje.Mostrar_MENSAJE_FILANOSELECCIONADO(this);
            return 0;
        }
        ModeloTabla modeloTablaProducto = (ModeloTabla) tablaProducto.getModel();
        return (Integer)modeloTablaProducto.getValueAt(numFila, 0); // se retorna el id de la fila seleccionada
    }
    
    
    private void consultarProducto(){
        ModeloTabla modeloTablaProducto = (ModeloTabla) tablaProducto.getModel();
        modeloTablaProducto.eliminarTotalFilas();
        String nombre = textobuscar.getText().trim().toUpperCase();
        try {
            GestionarProductoServicio gestionarProductoServicio = new GestionarProductoServicio();
            listaProducto = gestionarProductoServicio.buscarPorNombre(nombre);
            if(listaProducto!=null && listaProducto.size()>0){
                for(Producto producto : listaProducto){
                    Fila fila = new Fila();
                    fila.agregarValorCelda(producto.getCodigo());
                    fila.agregarValorCelda(producto.getNombre());
                    fila.agregarValorCelda(producto.getTipoProducto().getNombre());
                    fila.agregarValorCelda(producto.getUnidadDeMedida().getNombre());
                    fila.agregarValorCelda(producto.getMarca().getNombre());
                    fila.agregarValorCelda(producto.getDescripcion());
                    fila.agregarValorCelda(producto.getStock());
                    fila.agregarValorCelda(producto.getPrecio());
                    modeloTablaProducto.agregarFila(fila);
                }  
                tablaProducto.setModel(modeloTablaProducto);
            }else{
                Mensaje.Mostrar_MENSAJE_NOSEENCONTRONINGUNRESULTADO(this);
                ponerFocoConSeleccionEnBuscar();
            }             
        } catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    
    private void ponerFocoConSeleccionEnBuscar() {
        textobuscar.selectAll();
        textobuscar.requestFocus();
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonCrear;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonModificar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JButton botonSeleccionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tablaProducto;
    private javax.swing.JTextField textobuscar;
    // End of variables declaration//GEN-END:variables
}
