/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appTienda.c1_presentacion.form;

import appTienda.c1_presentacion.form.util.FormGestionarConfiguracionEmpresa;
import appTienda.c1_presentacion.form.util.FormGestionarConfiguracionBackup;
import appTienda.c1_presentacion.util.Mensaje;
import appTienda.c2_aplicacion.servicio.GestionarBackupServicio;
import appTienda.c3_dominio.entidad.Backup;
import appTienda.c3_dominio.entidad.Usuario;
import appTienda.c7_reportes.ConexionReportes;
import appTienda.c7_reportes.FormFechasReporte;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.net.URL;
import java.sql.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Osorio Perez Carlos - hacybeyker@gmail.com
 */
public class FormMenu extends javax.swing.JFrame {

    /**
     * Creates new form FormMenu
     */
    public static Usuario usuario;
    public static Date fechaInicio;    
    public static Date fechaFin;
    public static boolean confirmarFechas;
    
    public FormMenu() {
        mostrarLookAndFeel();
        mostrarIcono();
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }
    
    
    //para abrir desde login
    public FormMenu(Usuario usuario) {
        mostrarLookAndFeel();
        mostrarIcono();
        initComponents();
        FormMenu.usuario = usuario;
        setExtendedState(MAXIMIZED_BOTH);
        verificarCargo(usuario.getEmpleado().getCargo().getNombre());
        confirmarFechas = false;
    }
    
    private void mostrarIcono() {        
        URL recurso = getClass().getResource("/appTienda/c5_recursos/iconos/logox32.png");
        Image icono = Toolkit.getDefaultToolkit().createImage(recurso);
        setIconImage(icono);
    }

    private void mostrarLookAndFeel() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }
    
    public void verificarCargo(String cargo){
        switch(cargo){
            case "VENTA": 
                menuEmpleado.setEnabled(false);
                menuCargo.setEnabled(false);
                break;
            case "SISTEMAS": 
                break;
            case "GERENTE": 
                break;   
            default:
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoLookAndFeel = new javax.swing.ButtonGroup();
        toolBarAccesosDirectos = new javax.swing.JToolBar();
        botonADGestionarProducto = new javax.swing.JButton();
        botonADRegistrarVenta = new javax.swing.JButton();
        botonADRegistrarCliente = new javax.swing.JButton();
        botonADCalculadora = new javax.swing.JButton();
        botonADReportes = new javax.swing.JButton();
        botonADConfiguracion = new javax.swing.JButton();
        botonADInternet = new javax.swing.JButton();
        botonADSalir = new javax.swing.JButton();
        etiquetaFondo = new javax.swing.JLabel();
        menuPrincipal = new javax.swing.JMenuBar();
        menuGestionar = new javax.swing.JMenu();
        menuProducto = new javax.swing.JMenuItem();
        menuCliente = new javax.swing.JMenuItem();
        menuEmpleado = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuTipodeProducto = new javax.swing.JMenuItem();
        menuUnidadDeMedida = new javax.swing.JMenuItem();
        menuMarca = new javax.swing.JMenuItem();
        menuCargo = new javax.swing.JMenuItem();
        menuProcesos = new javax.swing.JMenu();
        menuPedido = new javax.swing.JMenuItem();
        menuHerramientas = new javax.swing.JMenu();
        menuConfiguracion = new javax.swing.JMenuItem();
        menuTeclado = new javax.swing.JMenuItem();
        menuCalculadora = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        menuReportesCliente = new javax.swing.JMenu();
        menuReportesClienteListaTodos = new javax.swing.JMenuItem();
        menuReportesClienteCompraronMas = new javax.swing.JMenuItem();
        menuReportesClienteCompraronMasPorFecha = new javax.swing.JMenuItem();
        menuReportesEmpleado = new javax.swing.JMenu();
        menuReportesEmpleadoListaTodos = new javax.swing.JMenuItem();
        menuReportesEmpleadoVendieronMas = new javax.swing.JMenuItem();
        menuReportesEmpleadoVendieronMasPorFecha = new javax.swing.JMenuItem();
        menuReportesProducto = new javax.swing.JMenu();
        menuReportesProductoListaTodos = new javax.swing.JMenuItem();
        menuReportesProductoVendidosMas = new javax.swing.JMenuItem();
        menuReportesProductoVendidosMasPorFecha = new javax.swing.JMenuItem();
        menuReportesProductoBajoStock = new javax.swing.JMenuItem();
        menuReportesPedido = new javax.swing.JMenu();
        TodosLosPedidosSinDetalle = new javax.swing.JMenuItem();
        TodosLosPedidosSinDetallePorFechas = new javax.swing.JMenuItem();
        TodosLosPedidosConDetalle = new javax.swing.JMenuItem();
        TodosLosPedidosConDetallePorFechas = new javax.swing.JMenuItem();
        menuAplicacion = new javax.swing.JMenu();
        menuLookAndFeel = new javax.swing.JMenu();
        radiomenuNimbus = new javax.swing.JRadioButtonMenuItem();
        radiomenuMetal = new javax.swing.JRadioButtonMenuItem();
        radiomenuWindows = new javax.swing.JRadioButtonMenuItem();
        radiomenuJTattoo = new javax.swing.JRadioButtonMenuItem();
        radiomenuLiquid = new javax.swing.JRadioButtonMenuItem();
        menuAcercaDe = new javax.swing.JMenuItem();
        menuBackUp = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Software Tienda");

        toolBarAccesosDirectos.setRollover(true);
        toolBarAccesosDirectos.setOpaque(false);

        botonADGestionarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appTienda/c5_recursos/iconos/productox64.png"))); // NOI18N
        botonADGestionarProducto.setText("Producto");
        botonADGestionarProducto.setFocusable(false);
        botonADGestionarProducto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonADGestionarProducto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonADGestionarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonADGestionarProductoActionPerformed(evt);
            }
        });
        toolBarAccesosDirectos.add(botonADGestionarProducto);

        botonADRegistrarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appTienda/c5_recursos/iconos/ventax64.png"))); // NOI18N
        botonADRegistrarVenta.setText("Pedido");
        botonADRegistrarVenta.setFocusable(false);
        botonADRegistrarVenta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonADRegistrarVenta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonADRegistrarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonADRegistrarVentaActionPerformed(evt);
            }
        });
        toolBarAccesosDirectos.add(botonADRegistrarVenta);

        botonADRegistrarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appTienda/c5_recursos/iconos/clientex64.png"))); // NOI18N
        botonADRegistrarCliente.setText("Cliente");
        botonADRegistrarCliente.setFocusable(false);
        botonADRegistrarCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonADRegistrarCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonADRegistrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonADRegistrarClienteActionPerformed(evt);
            }
        });
        toolBarAccesosDirectos.add(botonADRegistrarCliente);

        botonADCalculadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appTienda/c5_recursos/iconos/calculadorax64.png"))); // NOI18N
        botonADCalculadora.setText("Calculadora");
        botonADCalculadora.setFocusable(false);
        botonADCalculadora.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonADCalculadora.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonADCalculadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonADCalculadoraActionPerformed(evt);
            }
        });
        toolBarAccesosDirectos.add(botonADCalculadora);

        botonADReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appTienda/c5_recursos/iconos/reportex64.png"))); // NOI18N
        botonADReportes.setText("Reporte");
        botonADReportes.setFocusable(false);
        botonADReportes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonADReportes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBarAccesosDirectos.add(botonADReportes);

        botonADConfiguracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appTienda/c5_recursos/iconos/configuracionx64.png"))); // NOI18N
        botonADConfiguracion.setText("Configuracion");
        botonADConfiguracion.setFocusable(false);
        botonADConfiguracion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonADConfiguracion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonADConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonADConfiguracionActionPerformed(evt);
            }
        });
        toolBarAccesosDirectos.add(botonADConfiguracion);

        botonADInternet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appTienda/c5_recursos/iconos/internetx64.png"))); // NOI18N
        botonADInternet.setText("Internet");
        botonADInternet.setFocusable(false);
        botonADInternet.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonADInternet.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonADInternet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonADInternetActionPerformed(evt);
            }
        });
        toolBarAccesosDirectos.add(botonADInternet);

        botonADSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appTienda/c5_recursos/iconos/salirmenux64.png"))); // NOI18N
        botonADSalir.setText("Salir");
        botonADSalir.setFocusable(false);
        botonADSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonADSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonADSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonADSalirActionPerformed(evt);
            }
        });
        toolBarAccesosDirectos.add(botonADSalir);

        getContentPane().add(toolBarAccesosDirectos, java.awt.BorderLayout.PAGE_START);

        etiquetaFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appTienda/c5_recursos/iconos/tienda02.jpg"))); // NOI18N
        etiquetaFondo.setText("jLabel1");
        getContentPane().add(etiquetaFondo, java.awt.BorderLayout.CENTER);

        menuPrincipal.setOpaque(false);

        menuGestionar.setText("Gestionar");

        menuProducto.setBackground(new java.awt.Color(255, 255, 255));
        menuProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appTienda/c5_recursos/iconos/productox32.png"))); // NOI18N
        menuProducto.setText("Gestionar Producto");
        menuProducto.setOpaque(true);
        menuProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProductoActionPerformed(evt);
            }
        });
        menuGestionar.add(menuProducto);

        menuCliente.setBackground(new java.awt.Color(255, 255, 255));
        menuCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appTienda/c5_recursos/iconos/clientex32.png"))); // NOI18N
        menuCliente.setText("Gestionar Cliente");
        menuCliente.setOpaque(true);
        menuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClienteActionPerformed(evt);
            }
        });
        menuGestionar.add(menuCliente);

        menuEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        menuEmpleado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appTienda/c5_recursos/iconos/Empleadox32.png"))); // NOI18N
        menuEmpleado.setText("Gestionar Empleado");
        menuEmpleado.setOpaque(true);
        menuEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEmpleadoActionPerformed(evt);
            }
        });
        menuGestionar.add(menuEmpleado);
        menuGestionar.add(jSeparator1);

        menuTipodeProducto.setBackground(new java.awt.Color(255, 255, 255));
        menuTipodeProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuTipodeProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appTienda/c5_recursos/iconos/TipoProductox32.png"))); // NOI18N
        menuTipodeProducto.setText("Gestioonar Tipo de Producto");
        menuTipodeProducto.setOpaque(true);
        menuTipodeProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTipodeProductoActionPerformed(evt);
            }
        });
        menuGestionar.add(menuTipodeProducto);

        menuUnidadDeMedida.setBackground(new java.awt.Color(255, 255, 255));
        menuUnidadDeMedida.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuUnidadDeMedida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appTienda/c5_recursos/iconos/unidaddemedidax32.png"))); // NOI18N
        menuUnidadDeMedida.setText("GestionarUnidad de Medida");
        menuUnidadDeMedida.setOpaque(true);
        menuUnidadDeMedida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUnidadDeMedidaActionPerformed(evt);
            }
        });
        menuGestionar.add(menuUnidadDeMedida);

        menuMarca.setBackground(new java.awt.Color(255, 255, 255));
        menuMarca.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuMarca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appTienda/c5_recursos/iconos/marcax32.png"))); // NOI18N
        menuMarca.setText("Gestionar Marca");
        menuMarca.setOpaque(true);
        menuMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMarcaActionPerformed(evt);
            }
        });
        menuGestionar.add(menuMarca);

        menuCargo.setBackground(new java.awt.Color(255, 255, 255));
        menuCargo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuCargo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appTienda/c5_recursos/iconos/Cargox32.png"))); // NOI18N
        menuCargo.setText("Gestionar Cargo");
        menuCargo.setOpaque(true);
        menuCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCargoActionPerformed(evt);
            }
        });
        menuGestionar.add(menuCargo);

        menuPrincipal.add(menuGestionar);

        menuProcesos.setText("Procesos");

        menuPedido.setBackground(new java.awt.Color(255, 255, 255));
        menuPedido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appTienda/c5_recursos/iconos/ventax32.png"))); // NOI18N
        menuPedido.setText("Registrar Pedido");
        menuPedido.setOpaque(true);
        menuPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPedidoActionPerformed(evt);
            }
        });
        menuProcesos.add(menuPedido);

        menuPrincipal.add(menuProcesos);

        menuHerramientas.setText("Herramientas");

        menuConfiguracion.setBackground(new java.awt.Color(255, 255, 255));
        menuConfiguracion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuConfiguracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appTienda/c5_recursos/iconos/configuracionx32.png"))); // NOI18N
        menuConfiguracion.setText("Configuración");
        menuConfiguracion.setOpaque(true);
        menuConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConfiguracionActionPerformed(evt);
            }
        });
        menuHerramientas.add(menuConfiguracion);

        menuTeclado.setBackground(new java.awt.Color(255, 255, 255));
        menuTeclado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuTeclado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appTienda/c5_recursos/iconos/tecladox32.png"))); // NOI18N
        menuTeclado.setText("Teclado");
        menuTeclado.setOpaque(true);
        menuTeclado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTecladoActionPerformed(evt);
            }
        });
        menuHerramientas.add(menuTeclado);

        menuCalculadora.setBackground(new java.awt.Color(255, 255, 255));
        menuCalculadora.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuCalculadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appTienda/c5_recursos/iconos/calculadorax32.png"))); // NOI18N
        menuCalculadora.setText("Calculadora");
        menuCalculadora.setOpaque(true);
        menuCalculadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCalculadoraActionPerformed(evt);
            }
        });
        menuHerramientas.add(menuCalculadora);

        jMenu1.setBackground(new java.awt.Color(255, 255, 255));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appTienda/c5_recursos/iconos/configuracionx32.png"))); // NOI18N
        jMenu1.setText("Configuración");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenu1.setOpaque(true);

        jMenuItem1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appTienda/c5_recursos/iconos/backupx32.png"))); // NOI18N
        jMenuItem1.setText("Backup");
        jMenuItem1.setOpaque(true);
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appTienda/c5_recursos/iconos/empresax32.png"))); // NOI18N
        jMenuItem2.setText("Empresa");
        jMenuItem2.setOpaque(true);
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        menuHerramientas.add(jMenu1);

        menuPrincipal.add(menuHerramientas);

        menuReportes.setText("Reportes");

        menuReportesCliente.setBackground(new java.awt.Color(255, 255, 255));
        menuReportesCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appTienda/c5_recursos/iconos/reporteClientex32.png"))); // NOI18N
        menuReportesCliente.setText("Clientes");
        menuReportesCliente.setOpaque(true);

        menuReportesClienteListaTodos.setBackground(new java.awt.Color(255, 255, 255));
        menuReportesClienteListaTodos.setText("Todos los clientes");
        menuReportesClienteListaTodos.setOpaque(true);
        menuReportesCliente.add(menuReportesClienteListaTodos);

        menuReportesClienteCompraronMas.setBackground(new java.awt.Color(255, 255, 255));
        menuReportesClienteCompraronMas.setText("Compraron más ");
        menuReportesClienteCompraronMas.setOpaque(true);
        menuReportesClienteCompraronMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReportesClienteCompraronMasActionPerformed(evt);
            }
        });
        menuReportesCliente.add(menuReportesClienteCompraronMas);

        menuReportesClienteCompraronMasPorFecha.setBackground(new java.awt.Color(255, 255, 255));
        menuReportesClienteCompraronMasPorFecha.setText("Compraron más por fechas");
        menuReportesClienteCompraronMasPorFecha.setOpaque(true);
        menuReportesCliente.add(menuReportesClienteCompraronMasPorFecha);

        menuReportes.add(menuReportesCliente);

        menuReportesEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        menuReportesEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appTienda/c5_recursos/iconos/reporteEmpleadosx32.png"))); // NOI18N
        menuReportesEmpleado.setText("Empleados");
        menuReportesEmpleado.setOpaque(true);

        menuReportesEmpleadoListaTodos.setBackground(new java.awt.Color(255, 255, 255));
        menuReportesEmpleadoListaTodos.setText("Todos los empleados");
        menuReportesEmpleadoListaTodos.setOpaque(true);
        menuReportesEmpleado.add(menuReportesEmpleadoListaTodos);

        menuReportesEmpleadoVendieronMas.setBackground(new java.awt.Color(255, 255, 255));
        menuReportesEmpleadoVendieronMas.setText("Vendieron más");
        menuReportesEmpleadoVendieronMas.setOpaque(true);
        menuReportesEmpleado.add(menuReportesEmpleadoVendieronMas);

        menuReportesEmpleadoVendieronMasPorFecha.setBackground(new java.awt.Color(255, 255, 255));
        menuReportesEmpleadoVendieronMasPorFecha.setText("Vendieron más por fecha");
        menuReportesEmpleadoVendieronMasPorFecha.setOpaque(true);
        menuReportesEmpleadoVendieronMasPorFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReportesEmpleadoVendieronMasPorFechaActionPerformed(evt);
            }
        });
        menuReportesEmpleado.add(menuReportesEmpleadoVendieronMasPorFecha);

        menuReportes.add(menuReportesEmpleado);

        menuReportesProducto.setBackground(new java.awt.Color(255, 255, 255));
        menuReportesProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appTienda/c5_recursos/iconos/reporteProductox32.png"))); // NOI18N
        menuReportesProducto.setText("Productos");
        menuReportesProducto.setOpaque(true);

        menuReportesProductoListaTodos.setBackground(new java.awt.Color(255, 255, 255));
        menuReportesProductoListaTodos.setText("Todos los productos");
        menuReportesProductoListaTodos.setOpaque(true);
        menuReportesProductoListaTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReportesProductoListaTodosActionPerformed(evt);
            }
        });
        menuReportesProducto.add(menuReportesProductoListaTodos);

        menuReportesProductoVendidosMas.setBackground(new java.awt.Color(255, 255, 255));
        menuReportesProductoVendidosMas.setText("Más vendidos");
        menuReportesProductoVendidosMas.setOpaque(true);
        menuReportesProductoVendidosMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReportesProductoVendidosMasActionPerformed(evt);
            }
        });
        menuReportesProducto.add(menuReportesProductoVendidosMas);

        menuReportesProductoVendidosMasPorFecha.setBackground(new java.awt.Color(255, 255, 255));
        menuReportesProductoVendidosMasPorFecha.setText("Más vendidos por fechas");
        menuReportesProductoVendidosMasPorFecha.setOpaque(true);
        menuReportesProductoVendidosMasPorFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReportesProductoVendidosMasPorFechaActionPerformed(evt);
            }
        });
        menuReportesProducto.add(menuReportesProductoVendidosMasPorFecha);

        menuReportesProductoBajoStock.setBackground(new java.awt.Color(255, 255, 255));
        menuReportesProductoBajoStock.setText("Con bajo stock");
        menuReportesProductoBajoStock.setOpaque(true);
        menuReportesProductoBajoStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReportesProductoBajoStockActionPerformed(evt);
            }
        });
        menuReportesProducto.add(menuReportesProductoBajoStock);

        menuReportes.add(menuReportesProducto);

        menuReportesPedido.setBackground(new java.awt.Color(255, 255, 255));
        menuReportesPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appTienda/c5_recursos/iconos/reportePedidox32.png"))); // NOI18N
        menuReportesPedido.setText("Pedidos");
        menuReportesPedido.setOpaque(true);

        TodosLosPedidosSinDetalle.setBackground(new java.awt.Color(255, 255, 255));
        TodosLosPedidosSinDetalle.setText("Todos los pedidos sin detalle");
        TodosLosPedidosSinDetalle.setOpaque(true);
        menuReportesPedido.add(TodosLosPedidosSinDetalle);

        TodosLosPedidosSinDetallePorFechas.setBackground(new java.awt.Color(255, 255, 255));
        TodosLosPedidosSinDetallePorFechas.setText("Todos los pedidos sin detalle por fechas");
        TodosLosPedidosSinDetallePorFechas.setOpaque(true);
        menuReportesPedido.add(TodosLosPedidosSinDetallePorFechas);

        TodosLosPedidosConDetalle.setBackground(new java.awt.Color(255, 255, 255));
        TodosLosPedidosConDetalle.setText("Todos los pedidos  con detalle");
        TodosLosPedidosConDetalle.setOpaque(true);
        menuReportesPedido.add(TodosLosPedidosConDetalle);

        TodosLosPedidosConDetallePorFechas.setBackground(new java.awt.Color(255, 255, 255));
        TodosLosPedidosConDetallePorFechas.setText("Todos los pedidos con detalle por fechas");
        TodosLosPedidosConDetallePorFechas.setOpaque(true);
        menuReportesPedido.add(TodosLosPedidosConDetallePorFechas);

        menuReportes.add(menuReportesPedido);

        menuPrincipal.add(menuReportes);

        menuAplicacion.setText("Aplicacion");

        menuLookAndFeel.setBackground(new java.awt.Color(255, 255, 255));
        menuLookAndFeel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appTienda/c5_recursos/iconos/personalizarx32.png"))); // NOI18N
        menuLookAndFeel.setText("Personalizar");
        menuLookAndFeel.setOpaque(true);

        radiomenuNimbus.setBackground(new java.awt.Color(255, 255, 255));
        grupoLookAndFeel.add(radiomenuNimbus);
        radiomenuNimbus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radiomenuNimbus.setSelected(true);
        radiomenuNimbus.setText("Nimbus");
        radiomenuNimbus.setOpaque(true);
        radiomenuNimbus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiomenuNimbusActionPerformed(evt);
            }
        });
        menuLookAndFeel.add(radiomenuNimbus);

        radiomenuMetal.setBackground(new java.awt.Color(255, 255, 255));
        grupoLookAndFeel.add(radiomenuMetal);
        radiomenuMetal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radiomenuMetal.setText("Metal");
        radiomenuMetal.setOpaque(true);
        radiomenuMetal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiomenuMetalActionPerformed(evt);
            }
        });
        menuLookAndFeel.add(radiomenuMetal);

        radiomenuWindows.setBackground(new java.awt.Color(255, 255, 255));
        grupoLookAndFeel.add(radiomenuWindows);
        radiomenuWindows.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radiomenuWindows.setText("Windows");
        radiomenuWindows.setOpaque(true);
        radiomenuWindows.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiomenuWindowsActionPerformed(evt);
            }
        });
        menuLookAndFeel.add(radiomenuWindows);

        radiomenuJTattoo.setBackground(new java.awt.Color(255, 255, 255));
        grupoLookAndFeel.add(radiomenuJTattoo);
        radiomenuJTattoo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radiomenuJTattoo.setText("JTattoo");
        radiomenuJTattoo.setOpaque(true);
        radiomenuJTattoo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiomenuJTattooActionPerformed(evt);
            }
        });
        menuLookAndFeel.add(radiomenuJTattoo);

        radiomenuLiquid.setBackground(new java.awt.Color(255, 255, 255));
        grupoLookAndFeel.add(radiomenuLiquid);
        radiomenuLiquid.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radiomenuLiquid.setText("Liquid");
        radiomenuLiquid.setOpaque(true);
        radiomenuLiquid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiomenuLiquidActionPerformed(evt);
            }
        });
        menuLookAndFeel.add(radiomenuLiquid);

        menuAplicacion.add(menuLookAndFeel);

        menuAcercaDe.setBackground(new java.awt.Color(255, 255, 255));
        menuAcercaDe.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuAcercaDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appTienda/c5_recursos/iconos/acercadex32.png"))); // NOI18N
        menuAcercaDe.setText("Acerca de");
        menuAcercaDe.setOpaque(true);
        menuAplicacion.add(menuAcercaDe);

        menuBackUp.setBackground(new java.awt.Color(255, 255, 255));
        menuBackUp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuBackUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appTienda/c5_recursos/iconos/backupx32.png"))); // NOI18N
        menuBackUp.setText("Backup");
        menuBackUp.setOpaque(true);
        menuBackUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBackUpActionPerformed(evt);
            }
        });
        menuAplicacion.add(menuBackUp);

        menuSalir.setBackground(new java.awt.Color(255, 255, 255));
        menuSalir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appTienda/c5_recursos/iconos/salirx32.png"))); // NOI18N
        menuSalir.setText("Salir");
        menuSalir.setOpaque(true);
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        menuAplicacion.add(menuSalir);

        menuPrincipal.add(menuAplicacion);

        setJMenuBar(menuPrincipal);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void radiomenuNimbusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiomenuNimbusActionPerformed
        // TODO add your handling code here:
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
            SwingUtilities.updateComponentTreeUI(this);
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            
        }
    }//GEN-LAST:event_radiomenuNimbusActionPerformed

    private void radiomenuMetalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiomenuMetalActionPerformed
        // TODO add your handling code here:
        try {
            UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
            SwingUtilities.updateComponentTreeUI(this);
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            
        } 
    }//GEN-LAST:event_radiomenuMetalActionPerformed

    private void radiomenuWindowsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiomenuWindowsActionPerformed
        // TODO add your handling code here:
        try {            
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            SwingUtilities.updateComponentTreeUI(this);
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            
        } 
    }//GEN-LAST:event_radiomenuWindowsActionPerformed

    private void radiomenuJTattooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiomenuJTattooActionPerformed
        // TODO add your handling code here:
        try {            
            UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel");
            SwingUtilities.updateComponentTreeUI(this);
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            
        }
    }//GEN-LAST:event_radiomenuJTattooActionPerformed

    private void radiomenuLiquidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiomenuLiquidActionPerformed
        // TODO add your handling code here:
        try {            
            UIManager.setLookAndFeel("com.birosoft.liquid.LiquidLookAndFeel");
            SwingUtilities.updateComponentTreeUI(this);
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            
        }
    }//GEN-LAST:event_radiomenuLiquidActionPerformed

    private void botonADSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonADSalirActionPerformed
        // TODO add your handling code here:        
        if(Mensaje.Mostrar_MENSAJE_PREGUNTAHACERBACKUP(null)){
            Backup backup;
            GestionarBackupServicio gestionarBackupServicio = new GestionarBackupServicio();    
            try {
                backup = gestionarBackupServicio.buscar();
                if(backup != null){
                    backup.realizarBackup();    
                    Mensaje.Mostrar_MENSAJE_BACKUPEXITOSO(null);
                }
            }catch(Exception ex){}
        }           
        this.dispose();
    }//GEN-LAST:event_botonADSalirActionPerformed

    private void botonADInternetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonADInternetActionPerformed
        // TODO add your handling code here:
        String direccion = "http://www.google.com";
        try{
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + direccion);
        }
        catch(Exception err){
            Mensaje.Mostrar_MENSAJE_INTERNETMAL(null);
        }
    }//GEN-LAST:event_botonADInternetActionPerformed

    private void botonADCalculadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonADCalculadoraActionPerformed
        // TODO add your handling code here:
        ejecutarCalculadora();
    }//GEN-LAST:event_botonADCalculadoraActionPerformed

    private void botonADGestionarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonADGestionarProductoActionPerformed
        // TODO add your handling code here:
        FormGestionarProducto formGestionarProducto = new FormGestionarProducto(this, true);
        formGestionarProducto.setVisible(true);  
    }//GEN-LAST:event_botonADGestionarProductoActionPerformed

    private void botonADRegistrarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonADRegistrarVentaActionPerformed
        // TODO add your handling code here:
        FormRegistrarPedido formRegistrarPedido = new FormRegistrarPedido(this, true);
        formRegistrarPedido.setVisible(true);
    }//GEN-LAST:event_botonADRegistrarVentaActionPerformed

    private void botonADRegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonADRegistrarClienteActionPerformed
        // TODO add your handling code here:
        FormGestionarCliente formGestionarCliente = new FormGestionarCliente(this, true);
        formGestionarCliente.setVisible(true);
    }//GEN-LAST:event_botonADRegistrarClienteActionPerformed

    private void menuProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProductoActionPerformed
        // TODO add your handling code here:
        FormGestionarProducto formGestionarProducto = new FormGestionarProducto(this, true);
        formGestionarProducto.setVisible(true);
    }//GEN-LAST:event_menuProductoActionPerformed

    private void menuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClienteActionPerformed
        // TODO add your handling code here:
        FormGestionarCliente formGestionarCliente = new FormGestionarCliente(this, true);
        formGestionarCliente.setVisible(true);
    }//GEN-LAST:event_menuClienteActionPerformed

    private void menuEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEmpleadoActionPerformed
        // TODO add your handling code here:
        FormGestionarEmpleado formGestionarEmpleado = new FormGestionarEmpleado(this, true);
        formGestionarEmpleado.setVisible(true); 
    }//GEN-LAST:event_menuEmpleadoActionPerformed

    private void menuTipodeProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTipodeProductoActionPerformed
        // TODO add your handling code here:
        FormGestionarTipoDeProducto formGestionarTipoDeProducto = new FormGestionarTipoDeProducto(this, true);
        formGestionarTipoDeProducto.setVisible(true);
    }//GEN-LAST:event_menuTipodeProductoActionPerformed

    private void menuCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCargoActionPerformed
        // TODO add your handling code here:
        FormGestionarCargo formGestionarCargo = new FormGestionarCargo(this, true);
        formGestionarCargo.setVisible(true);
    }//GEN-LAST:event_menuCargoActionPerformed

    private void menuPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPedidoActionPerformed
        // TODO add your handling code here:
        FormRegistrarPedido formRegistrarPedido = new FormRegistrarPedido(this, true);
        formRegistrarPedido.setVisible(true);
    }//GEN-LAST:event_menuPedidoActionPerformed

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
        // TODO add your handling code here:
        FormLogin formLogin = new FormLogin();
        formLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuSalirActionPerformed

    private void botonADConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonADConfiguracionActionPerformed
        // TODO add your handling code here:
        FormGestionarConfiguracion formGestionarConfiguracion = new FormGestionarConfiguracion(this, true);
        formGestionarConfiguracion.setVisible(true);
    }//GEN-LAST:event_botonADConfiguracionActionPerformed

    private void menuConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConfiguracionActionPerformed
        // TODO add your handling code here:
        FormGestionarConfiguracion formGestionarConfiguracion = new FormGestionarConfiguracion(this, true);
        formGestionarConfiguracion.setVisible(true);
    }//GEN-LAST:event_menuConfiguracionActionPerformed

    private void menuUnidadDeMedidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUnidadDeMedidaActionPerformed
        // TODO add your handling code here:
        FormGestionarUnidadDeMedida formGestionarUnidadDeMedida = new FormGestionarUnidadDeMedida(this, true);
        formGestionarUnidadDeMedida.setVisible(true);
    }//GEN-LAST:event_menuUnidadDeMedidaActionPerformed

    private void menuMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMarcaActionPerformed
        // TODO add your handling code here:
        FormGestionarMarca formGestionarMarca = new FormGestionarMarca(this, true);
        formGestionarMarca.setVisible(true);
    }//GEN-LAST:event_menuMarcaActionPerformed

    private void menuTecladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTecladoActionPerformed
        // TODO add your handling code here:
        ejecutarTeclado();
    }//GEN-LAST:event_menuTecladoActionPerformed

    private void menuCalculadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCalculadoraActionPerformed
        // TODO add your handling code here:
        ejecutarCalculadora();
    }//GEN-LAST:event_menuCalculadoraActionPerformed

    private void menuBackUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBackUpActionPerformed
        // TODO add your handling code here:  
        
    }//GEN-LAST:event_menuBackUpActionPerformed
   
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        FormGestionarConfiguracionBackup formGestionarConfiguracionBackup = new FormGestionarConfiguracionBackup(this, true);
        formGestionarConfiguracionBackup.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        FormGestionarConfiguracionEmpresa formGestionarConfiguracionEmpresa = new FormGestionarConfiguracionEmpresa(this, true);
        formGestionarConfiguracionEmpresa.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void menuReportesClienteCompraronMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportesClienteCompraronMasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuReportesClienteCompraronMasActionPerformed

    private void menuReportesProductoBajoStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportesProductoBajoStockActionPerformed
        // TODO add your handling code here:
        try {         
            String dir = System.getProperty ("user.dir")+"\\src\\appTienda\\c7_reportes\\productos\\ProductosConBajoStock.jrxml"; //para ejecutar en netbeans           
            JasperReport reporteJasper = JasperCompileManager.compileReport(dir);
            JasperPrint mostrarReporte = JasperFillManager.fillReport(reporteJasper, null,ConexionReportes.Conexion());
            JasperViewer viewReport = new JasperViewer(mostrarReporte,false);  
            viewReport.setVisible(true);
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(this, "JasperReport HOLA : "+ex.getMessage());
        }    
    }//GEN-LAST:event_menuReportesProductoBajoStockActionPerformed

    private void menuReportesProductoListaTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportesProductoListaTodosActionPerformed
        // TODO add your handling code here:
        try {         
            String dir = System.getProperty ("user.dir")+"\\src\\appTienda\\c7_reportes\\productos\\TodosLosProductos.jrxml"; //para ejecutar en netbeans           
            JasperReport reporteJasper = JasperCompileManager.compileReport(dir);
            JasperPrint mostrarReporte = JasperFillManager.fillReport(reporteJasper, null,ConexionReportes.Conexion());
            JasperViewer viewReport = new JasperViewer(mostrarReporte,false);  
            viewReport.setVisible(true);
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(this, "JasperReport HOLA : "+ex.getMessage());
        } 
    }//GEN-LAST:event_menuReportesProductoListaTodosActionPerformed

    private void menuReportesProductoVendidosMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportesProductoVendidosMasActionPerformed
        // TODO add your handling code here:
        try {         
            String dir = System.getProperty ("user.dir")+"\\src\\appTienda\\c7_reportes\\productos\\ProductosMasVendidos.jrxml"; //para ejecutar en netbeans           
            JasperReport reporteJasper = JasperCompileManager.compileReport(dir);
            JasperPrint mostrarReporte = JasperFillManager.fillReport(reporteJasper, null,ConexionReportes.Conexion());
            JasperViewer viewReport = new JasperViewer(mostrarReporte,false);  
            viewReport.setVisible(true);
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(this, "JasperReport HOLA : "+ex.getMessage());
        } 
    }//GEN-LAST:event_menuReportesProductoVendidosMasActionPerformed

    private void menuReportesProductoVendidosMasPorFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportesProductoVendidosMasPorFechaActionPerformed
        // TODO add your handling code here:
        FormFechasReporte formFechasReporte = new FormFechasReporte(null,3);
        formFechasReporte.setVisible(true);
        if(confirmarFechas){
            try{
                String dir = System.getProperty ("user.dir")+"\\src\\appTienda\\c7_reportes\\productos\\ProductosMasVendidosPorFechas.jrxml"; //para ejecutar en netbeans
                Map parametros = new HashMap();
                parametros.put("fechaInicio", fechaInicio);
                parametros.put("fechaFin", fechaFin);
                JasperReport reporteJasper = JasperCompileManager.compileReport(dir);
                JasperPrint mostrarReporte = JasperFillManager.fillReport(reporteJasper, parametros,ConexionReportes.Conexion());
                JasperViewer viewReport = new JasperViewer(mostrarReporte,false);
                viewReport.setVisible(true);
            }catch (JRException ex) {
                JOptionPane.showMessageDialog(this, "JasperReport HOLA : "+ex.getMessage());
            }
        }else{
            
        }
    }//GEN-LAST:event_menuReportesProductoVendidosMasPorFechaActionPerformed

    private void menuReportesEmpleadoVendieronMasPorFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportesEmpleadoVendieronMasPorFechaActionPerformed
        // TODO add your handling code here:
        FormFechasReporte formFechasReporte = new FormFechasReporte(null,2);
        formFechasReporte.setVisible(true);
        if(confirmarFechas){
            try{            
                String dir = System.getProperty ("user.dir")+"\\src\\appTienda\\c7_reportes\\empleados\\EmpleadoVentasPorFecha.jrxml"; //para ejecutar en netbeans
                Map parametros = new HashMap();
                parametros.put("fechaInicio", fechaInicio);
                parametros.put("fechaFin", fechaFin);
                JasperReport reporteJasper = JasperCompileManager.compileReport(dir);
                JasperPrint mostrarReporte = JasperFillManager.fillReport(reporteJasper, parametros,ConexionReportes.Conexion());
                JasperViewer viewReport = new JasperViewer(mostrarReporte,false);  
                viewReport.setVisible(true);
            }catch (JRException ex) {
                JOptionPane.showMessageDialog(this, "JasperReport HOLA : "+ex.getMessage());
            }
        }else{
            
        }
    }//GEN-LAST:event_menuReportesEmpleadoVendieronMasPorFechaActionPerformed
            
    
    private void ejecutarCalculadora(){
        try {            
            Runtime.getRuntime().exec("calc");//assim
            //Runtime.getRuntime().exec("C:\\Windows\\System32\\calc.exe"); 
        } catch (IOException ex) {
            Mensaje.Mostrar_MENSAJE_CALCULADORAMAL(null);
        }
    }
    
    private void ejecutarTeclado(){
        try {            
            Runtime.getRuntime().exec("cmd /c C:\\Windows\\System32\\osk.exe");
        } catch (IOException ex) {
            Mensaje.Mostrar_MENSAJE_TECLADORAMAL(null);
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem TodosLosPedidosConDetalle;
    private javax.swing.JMenuItem TodosLosPedidosConDetallePorFechas;
    private javax.swing.JMenuItem TodosLosPedidosSinDetalle;
    private javax.swing.JMenuItem TodosLosPedidosSinDetallePorFechas;
    private javax.swing.JButton botonADCalculadora;
    private javax.swing.JButton botonADConfiguracion;
    private javax.swing.JButton botonADGestionarProducto;
    private javax.swing.JButton botonADInternet;
    private javax.swing.JButton botonADRegistrarCliente;
    private javax.swing.JButton botonADRegistrarVenta;
    private javax.swing.JButton botonADReportes;
    private javax.swing.JButton botonADSalir;
    private javax.swing.JLabel etiquetaFondo;
    private javax.swing.ButtonGroup grupoLookAndFeel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem menuAcercaDe;
    private javax.swing.JMenu menuAplicacion;
    private javax.swing.JMenuItem menuBackUp;
    private javax.swing.JMenuItem menuCalculadora;
    private javax.swing.JMenuItem menuCargo;
    private javax.swing.JMenuItem menuCliente;
    private javax.swing.JMenuItem menuConfiguracion;
    private javax.swing.JMenuItem menuEmpleado;
    private javax.swing.JMenu menuGestionar;
    private javax.swing.JMenu menuHerramientas;
    private javax.swing.JMenu menuLookAndFeel;
    private javax.swing.JMenuItem menuMarca;
    private javax.swing.JMenuItem menuPedido;
    private javax.swing.JMenuBar menuPrincipal;
    private javax.swing.JMenu menuProcesos;
    private javax.swing.JMenuItem menuProducto;
    private javax.swing.JMenu menuReportes;
    private javax.swing.JMenu menuReportesCliente;
    private javax.swing.JMenuItem menuReportesClienteCompraronMas;
    private javax.swing.JMenuItem menuReportesClienteCompraronMasPorFecha;
    private javax.swing.JMenuItem menuReportesClienteListaTodos;
    private javax.swing.JMenu menuReportesEmpleado;
    private javax.swing.JMenuItem menuReportesEmpleadoListaTodos;
    private javax.swing.JMenuItem menuReportesEmpleadoVendieronMas;
    private javax.swing.JMenuItem menuReportesEmpleadoVendieronMasPorFecha;
    private javax.swing.JMenu menuReportesPedido;
    private javax.swing.JMenu menuReportesProducto;
    private javax.swing.JMenuItem menuReportesProductoBajoStock;
    private javax.swing.JMenuItem menuReportesProductoListaTodos;
    private javax.swing.JMenuItem menuReportesProductoVendidosMas;
    private javax.swing.JMenuItem menuReportesProductoVendidosMasPorFecha;
    private javax.swing.JMenuItem menuSalir;
    private javax.swing.JMenuItem menuTeclado;
    private javax.swing.JMenuItem menuTipodeProducto;
    private javax.swing.JMenuItem menuUnidadDeMedida;
    private javax.swing.JRadioButtonMenuItem radiomenuJTattoo;
    private javax.swing.JRadioButtonMenuItem radiomenuLiquid;
    private javax.swing.JRadioButtonMenuItem radiomenuMetal;
    private javax.swing.JRadioButtonMenuItem radiomenuNimbus;
    private javax.swing.JRadioButtonMenuItem radiomenuWindows;
    private javax.swing.JToolBar toolBarAccesosDirectos;
    // End of variables declaration//GEN-END:variables
}
